"""
This type stub file was generated by pyright.
"""

import asyncio
import urllib.parse
from __future__ import annotations
from uvicorn._types import WWWScope

class ClientDisconnected(OSError):
    ...


def get_remote_addr(transport: asyncio.Transport) -> tuple[str, int] | None:
    ...

def get_local_addr(transport: asyncio.Transport) -> tuple[str, int] | None:
    ...

def is_ssl(transport: asyncio.Transport) -> bool:
    ...

def get_client_addr(scope: WWWScope) -> str:
    ...

def get_path_with_query_string(scope: WWWScope) -> str:
    ...

