"""
This type stub file was generated by pyright.
"""

import zlib
from __future__ import annotations
from collections.abc import Sequence
from typing import Any
from .. import frames
from ..exceptions import DuplicateParameter, InvalidParameterName, InvalidParameterValue, NegotiationError, PayloadTooBig, ProtocolError
from ..typing import ExtensionName, ExtensionParameter
from .base import ClientExtensionFactory, Extension, ServerExtensionFactory

__all__ = ["PerMessageDeflate", "ClientPerMessageDeflateFactory", "enable_client_permessage_deflate", "ServerPerMessageDeflateFactory", "enable_server_permessage_deflate"]
_EMPTY_UNCOMPRESSED_BLOCK = ...
_MAX_WINDOW_BITS_VALUES = ...
class PerMessageDeflate(Extension):
    """
    Per-Message Deflate extension.

    """
    name = ...
    def __init__(self, remote_no_context_takeover: bool, local_no_context_takeover: bool, remote_max_window_bits: int, local_max_window_bits: int, compress_settings: dict[Any, Any] | None = ...) -> None:
        """
        Configure the Per-Message Deflate extension.

        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def decode(self, frame: frames.Frame, *, max_size: int | None = ...) -> frames.Frame:
        """
        Decode an incoming frame.

        """
        ...
    
    def encode(self, frame: frames.Frame) -> frames.Frame:
        """
        Encode an outgoing frame.

        """
        ...
    


class ClientPerMessageDeflateFactory(ClientExtensionFactory):
    """
    Client-side extension factory for the Per-Message Deflate extension.

    Parameters behave as described in `section 7.1 of RFC 7692`_.

    .. _section 7.1 of RFC 7692: https://datatracker.ietf.org/doc/html/rfc7692#section-7.1

    Set them to :obj:`True` to include them in the negotiation offer without a
    value or to an integer value to include them with this value.

    Args:
        server_no_context_takeover: Prevent server from using context takeover.
        client_no_context_takeover: Prevent client from using context takeover.
        server_max_window_bits: Maximum size of the server's LZ77 sliding window
            in bits, between 8 and 15.
        client_max_window_bits: Maximum size of the client's LZ77 sliding window
            in bits, between 8 and 15, or :obj:`True` to indicate support without
            setting a limit.
        compress_settings: Additional keyword arguments for :func:`zlib.compressobj`,
            excluding ``wbits``.

    """
    name = ...
    def __init__(self, server_no_context_takeover: bool = ..., client_no_context_takeover: bool = ..., server_max_window_bits: int | None = ..., client_max_window_bits: int | bool | None = ..., compress_settings: dict[str, Any] | None = ...) -> None:
        """
        Configure the Per-Message Deflate extension factory.

        """
        ...
    
    def get_request_params(self) -> list[ExtensionParameter]:
        """
        Build request parameters.

        """
        ...
    
    def process_response_params(self, params: Sequence[ExtensionParameter], accepted_extensions: Sequence[Extension]) -> PerMessageDeflate:
        """
        Process response parameters.

        Return an extension instance.

        """
        ...
    


def enable_client_permessage_deflate(extensions: Sequence[ClientExtensionFactory] | None) -> Sequence[ClientExtensionFactory]:
    """
    Enable Per-Message Deflate with default settings in client extensions.

    If the extension is already present, perhaps with non-default settings,
    the configuration isn't changed.

    """
    ...

class ServerPerMessageDeflateFactory(ServerExtensionFactory):
    """
    Server-side extension factory for the Per-Message Deflate extension.

    Parameters behave as described in `section 7.1 of RFC 7692`_.

    .. _section 7.1 of RFC 7692: https://datatracker.ietf.org/doc/html/rfc7692#section-7.1

    Set them to :obj:`True` to include them in the negotiation offer without a
    value or to an integer value to include them with this value.

    Args:
        server_no_context_takeover: Prevent server from using context takeover.
        client_no_context_takeover: Prevent client from using context takeover.
        server_max_window_bits: Maximum size of the server's LZ77 sliding window
            in bits, between 8 and 15.
        client_max_window_bits: Maximum size of the client's LZ77 sliding window
            in bits, between 8 and 15.
        compress_settings: Additional keyword arguments for :func:`zlib.compressobj`,
            excluding ``wbits``.
        require_client_max_window_bits: Do not enable compression at all if
            client doesn't advertise support for ``client_max_window_bits``;
            the default behavior is to enable compression without enforcing
            ``client_max_window_bits``.

    """
    name = ...
    def __init__(self, server_no_context_takeover: bool = ..., client_no_context_takeover: bool = ..., server_max_window_bits: int | None = ..., client_max_window_bits: int | None = ..., compress_settings: dict[str, Any] | None = ..., require_client_max_window_bits: bool = ...) -> None:
        """
        Configure the Per-Message Deflate extension factory.

        """
        ...
    
    def process_request_params(self, params: Sequence[ExtensionParameter], accepted_extensions: Sequence[Extension]) -> tuple[list[ExtensionParameter], PerMessageDeflate]:
        """
        Process request parameters.

        Return response params and an extension instance.

        """
        ...
    


def enable_server_permessage_deflate(extensions: Sequence[ServerExtensionFactory] | None) -> Sequence[ServerExtensionFactory]:
    """
    Enable Per-Message Deflate with default settings in server extensions.

    If the extension is already present, perhaps with non-default settings,
    the configuration isn't changed.

    """
    ...

