"""
This type stub file was generated by pyright.
"""

class PydubException(Exception):
    """
    Base class for any Pydub exception
    """
    ...


class TooManyMissingFrames(PydubException):
    ...


class InvalidDuration(PydubException):
    ...


class InvalidTag(PydubException):
    ...


class InvalidID3TagVersion(PydubException):
    ...


class CouldntDecodeError(PydubException):
    ...


class CouldntEncodeError(PydubException):
    ...


class MissingAudioParameter(PydubException):
    ...


