"""
This type stub file was generated by pyright.
"""

"""

"""
converter_logger = ...
def log_conversion(conversion_command): # -> None:
    ...

def log_subprocess_output(output): # -> None:
    ...

