"""
This type stub file was generated by pyright.
"""

import math
import typing
import uuid
from __future__ import annotations

T = typing.TypeVar("T")
class Convertor(typing.Generic[T]):
    regex: typing.ClassVar[str] = ...
    def convert(self, value: str) -> T:
        ...
    
    def to_string(self, value: T) -> str:
        ...
    


class StringConvertor(Convertor[str]):
    regex = ...
    def convert(self, value: str) -> str:
        ...
    
    def to_string(self, value: str) -> str:
        ...
    


class PathConvertor(Convertor[str]):
    regex = ...
    def convert(self, value: str) -> str:
        ...
    
    def to_string(self, value: str) -> str:
        ...
    


class IntegerConvertor(Convertor[int]):
    regex = ...
    def convert(self, value: str) -> int:
        ...
    
    def to_string(self, value: int) -> str:
        ...
    


class FloatConvertor(Convertor[float]):
    regex = ...
    def convert(self, value: str) -> float:
        ...
    
    def to_string(self, value: float) -> str:
        ...
    


class UUIDConvertor(Convertor[uuid.UUID]):
    regex = ...
    def convert(self, value: str) -> uuid.UUID:
        ...
    
    def to_string(self, value: uuid.UUID) -> str:
        ...
    


CONVERTOR_TYPES: dict[str, Convertor[typing.Any]] = ...
def register_url_convertor(key: str, convertor: Convertor[typing.Any]) -> None:
    ...

