"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from typing import ClassVar, TYPE_CHECKING
from rich.console import RenderableType
from rich.style import Style
from rich.text import Text, TextType
from textual.app import RenderResult
from textual.binding import Binding, BindingType
from textual.events import Click
from textual.geometry import Size
from textual.message import Message
from textual.reactive import reactive
from textual.widgets._static import Static
from typing_extensions import Self

"""Provides the base code and implementations of toggle widgets.

In particular it provides `Checkbox`, `RadioButton` and `RadioSet`.
"""
if TYPE_CHECKING:
    ...
class ToggleButton(Static, can_focus=True):
    """Base toggle button widget.

    Warning:
        `ToggleButton` should be considered to be an internal class; it
        exists to serve as the common core of [Checkbox][textual.widgets.Checkbox] and
        [RadioButton][textual.widgets.RadioButton].
    """
    ALLOW_SELECT = ...
    BINDINGS: ClassVar[list[BindingType]] = ...
    COMPONENT_CLASSES: ClassVar[set[str]] = ...
    DEFAULT_CSS = ...
    BUTTON_LEFT: str = ...
    BUTTON_INNER: str = ...
    BUTTON_RIGHT: str = ...
    value: reactive[bool] = ...
    def __init__(self, label: TextType = ..., value: bool = ..., button_first: bool = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., tooltip: RenderableType | None = ...) -> None:
        """Initialise the toggle.

        Args:
            label: The label for the toggle.
            value: The initial value of the toggle.
            button_first: Should the button come before the label, or after?
            name: The name of the toggle.
            id: The ID of the toggle in the DOM.
            classes: The CSS classes of the toggle.
            disabled: Whether the button is disabled or not.
            tooltip: RenderableType | None = None,
        """
        ...
    
    @property
    def label(self) -> Text:
        """The label associated with the button."""
        ...
    
    @label.setter
    def label(self, label: TextType) -> None:
        ...
    
    def render(self) -> RenderResult:
        """Render the content of the widget.

        Returns:
            The content to render for the widget.
        """
        ...
    
    def get_content_width(self, container: Size, viewport: Size) -> int:
        ...
    
    def get_content_height(self, container: Size, viewport: Size, width: int) -> int:
        ...
    
    def toggle(self) -> Self:
        """Toggle the value of the widget.

        Returns:
            The `ToggleButton` instance.
        """
        ...
    
    def action_toggle_button(self) -> None:
        """Toggle the value of the widget when called as an action.

        This would normally be used for a keyboard binding.
        """
        ...
    
    class Changed(Message):
        """Posted when the value of the toggle button changes."""
        def __init__(self, toggle_button: ToggleButton, value: bool) -> None:
            """Initialise the message.

            Args:
                toggle_button: The toggle button sending the message.
                value: The value of the toggle button.
            """
            ...
        
    
    
    def watch_value(self) -> None:
        """React to the value being changed.

        When triggered, the CSS class `-on` is applied to the widget if
        `value` has become `True`, or it is removed if it has become
        `False`. Subsequently a related `Changed` event will be posted.
        """
        ...
    


