"""
This type stub file was generated by pyright.
"""

import ipaddress
import re
import typing
import idna
from __future__ import annotations
from ._exceptions import InvalidURL

"""
An implementation of `urlparse` that provides URL validation and normalization
as described by RFC3986.

We rely on this implementation rather than the one in Python's stdlib, because:

* It provides more complete URL validation.
* It properly differentiates between an empty querystring and an absent querystring,
  to distinguish URLs with a trailing '?'.
* It handles scheme, hostname, port, and path normalization.
* It supports IDNA hostnames, normalizing them to their encoded form.
* The API supports passing individual components, as well as the complete URL string.

Previously we relied on the excellent `rfc3986` package to handle URL parsing and
validation, but this module provides a simpler alternative, with less indirection
required.
"""
MAX_URL_LENGTH = ...
UNRESERVED_CHARACTERS = ...
SUB_DELIMS = ...
PERCENT_ENCODED_REGEX = ...
FRAG_SAFE = ...
QUERY_SAFE = ...
PATH_SAFE = ...
USERNAME_SAFE = ...
PASSWORD_SAFE = ...
USERINFO_SAFE = ...
URL_REGEX = ...
AUTHORITY_REGEX = ...
COMPONENT_REGEX = ...
IPv4_STYLE_HOSTNAME = ...
IPv6_STYLE_HOSTNAME = ...
class ParseResult(typing.NamedTuple):
    scheme: str
    userinfo: str
    host: str
    port: int | None
    path: str
    query: str | None
    fragment: str | None
    @property
    def authority(self) -> str:
        ...
    
    @property
    def netloc(self) -> str:
        ...
    
    def copy_with(self, **kwargs: str | None) -> ParseResult:
        ...
    
    def __str__(self) -> str:
        ...
    


def urlparse(url: str = ..., **kwargs: str | None) -> ParseResult:
    ...

def encode_host(host: str) -> str:
    ...

def normalize_port(port: str | int | None, scheme: str) -> int | None:
    ...

def validate_path(path: str, has_scheme: bool, has_authority: bool) -> None:
    """
    Path validation rules that depend on if the URL contains
    a scheme or authority component.

    See https://datatracker.ietf.org/doc/html/rfc3986.html#section-3.3
    """
    ...

def normalize_path(path: str) -> str:
    """
    Drop "." and ".." segments from a URL path.

    For example:

        normalize_path("/path/./to/somewhere/..") == "/path/to"
    """
    ...

def PERCENT(string: str) -> str:
    ...

def percent_encoded(string: str, safe: str) -> str:
    """
    Use percent-encoding to quote a string.
    """
    ...

def quote(string: str, safe: str) -> str:
    """
    Use percent-encoding to quote a string, omitting existing '%xx' escape sequences.

    See: https://www.rfc-editor.org/rfc/rfc3986#section-2.1

    * `string`: The string to be percent-escaped.
    * `safe`: A string containing characters that may be treated as safe, and do not
        need to be escaped. Unreserved characters are always treated as safe.
        See: https://www.rfc-editor.org/rfc/rfc3986#section-2.3
    """
    ...

