"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from typing import NamedTuple

class URL(NamedTuple):
    protocol: str | None
    slashes: bool
    auth: str | None
    port: str | None
    hostname: str | None
    hash: str | None
    search: str | None
    pathname: str | None
    ...


