"""
This type stub file was generated by pyright.
"""

import threading
from __future__ import annotations
from queue import Queue
from typing import IO
from typing_extensions import Final

MAX_QUEUED_WRITES: Final[int] = ...
class WriterThread(threading.Thread):
    """A thread / file-like to do writes to stdout in the background."""
    def __init__(self, file: IO[str]) -> None:
        ...
    
    def write(self, text: str) -> None:
        """Write text. Text will be enqueued for writing.

        Args:
            text: Text to write to the file.
        """
        ...
    
    def isatty(self) -> bool:
        """Pretend to be a terminal.

        Returns:
            True.
        """
        ...
    
    def fileno(self) -> int:
        """Get file handle number.

        Returns:
            File number of proxied file.
        """
        ...
    
    def flush(self) -> None:
        """Flush the file (a no-op, because flush is done in the thread)."""
        ...
    
    def run(self) -> None:
        """Run the thread."""
        ...
    
    def stop(self) -> None:
        """Stop the thread, and block until it finished."""
        ...
    


