"""
This type stub file was generated by pyright.
"""

from ..common.utils import charCodeAt, unescapeAll

"""Parse link title
"""
class _Result:
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def parseLinkTitle(string: str, pos: int, maximum: int) -> _Result:
    ...

