"""
This type stub file was generated by pyright.
"""

import re
from __future__ import annotations
from ..common.utils import charStrAt, isStrSpace
from .state_block import StateBlock

headerLineRe = ...
enclosingPipesRe = ...
def getLine(state: StateBlock, line: int) -> str:
    ...

def escapedSplit(string: str) -> list[str]:
    ...

def table(state: StateBlock, startLine: int, endLine: int, silent: bool) -> bool:
    ...

