"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from bisect import bisect_right
from rich.text import Text
from textual._cells import cell_len, cell_width_to_column_index
from textual._wrap import compute_wrap_offsets
from textual.document._document import DocumentBase, Location
from textual.expand_tabs import expand_tabs_inline, get_tab_widths
from textual.geometry import Offset, clamp

VerticalOffset = int
LineIndex = int
SectionOffset = int
class WrappedDocument:
    """A view into a Document which wraps the document at a certain
    width and can be queried to retrieve lines from the *wrapped* version
    of the document.

    Allows for incremental updates, ensuring that we only re-wrap ranges of the document
    that were influenced by edits.
    """
    def __init__(self, document: DocumentBase, width: int = ..., tab_width: int = ...) -> None:
        """Construct a WrappedDocument.

        By default, a WrappedDocument is wrapped with width=0 (no wrapping).
        To wrap the document, use the wrap() method.

        Args:
            document: The document to wrap.
            width: The width to wrap at.
            tab_width: The maximum width to consider for tab characters.
        """
        ...
    
    @property
    def wrapped(self) -> bool:
        """True if the content is wrapped. This is not the same as wrapping being "enabled".
        For example, an empty document can have wrapping enabled, but no wrapping has actually
        occurred.

        In other words, this is True if the length of any line in the document is greater
        than the available width."""
        ...
    
    def wrap(self, width: int, tab_width: int | None = ...) -> None:
        """Wrap and cache all lines in the document.

        Args:
            width: The width to wrap at. 0 for no wrapping.
            tab_width: The maximum width to consider for tab characters. If None,
                reuse the  tab width.
        """
        ...
    
    @property
    def lines(self) -> list[list[str]]:
        """The lines of the wrapped version of the Document.

        Each index in the returned list represents a line index in the raw
        document. The list[str] at each index is the content of the raw document line
        split into multiple lines via wrapping.

        Note that this is expensive to compute and is not cached.

        Returns:
            A list of lines from the wrapped version of the document.
        """
        ...
    
    @property
    def height(self) -> int:
        """The height of the wrapped document."""
        ...
    
    def wrap_range(self, start: Location, old_end: Location, new_end: Location) -> None:
        """Incrementally recompute wrapping based on a performed edit.

        This must be called *after* the source document has been edited.

        Args:
            start: The start location of the edit that was performed in document-space.
            old_end: The old end location of the edit in document-space.
            new_end: The new end location of the edit in document-space.
        """
        ...
    
    def offset_to_location(self, offset: Offset) -> Location:
        """Given an offset within the wrapped/visual display of the document,
        return the corresponding location in the document.

        Args:
            offset: The y-offset within the document.

        Raises:
            ValueError: When the given offset does not correspond to a line
                in the document.

        Returns:
            The Location in the document corresponding to the given offset.
        """
        ...
    
    def location_to_offset(self, location: Location) -> Offset:
        """
        Convert a location in the document to an offset within the wrapped/visual display of the document.

        Args:
            location: The location in the document.

        Returns:
            The Offset in the document's visual display corresponding to the given location.
        """
        ...
    
    def get_target_document_column(self, line_index: int, x_offset: int, y_offset: int) -> int:
        """Given a line index and the offsets within the wrapped version of that
        line, return the corresponding column index in the raw document.

        Args:
             line_index: The index of the line in the document.
             x_offset: The x-offset within the wrapped line.
             y_offset: The y-offset within the wrapped line (supports negative indexing).

        Returns:
            The column index corresponding to the line index and y offset.
        """
        ...
    
    def get_sections(self, line_index: int) -> list[str]:
        """Return the sections for the given line index.

        When wrapping is enabled, a single line in the document can visually span
        multiple lines. The list returned represents that visually (each string in
        the list represents a single section (y-offset) after wrapping happens).

        Args:
            line_index: The index of the line to get sections for.

        Returns:
            The wrapped line as a list of strings.
        """
        ...
    
    def get_offsets(self, line_index: int) -> list[int]:
        """Given a line index, get the offsets within that line where wrapping
        should occur for the current document.

        Args:
            line_index: The index of the line within the document.

        Raises:
            ValueError: When `line_index` is out of bounds.

        Returns:
            The offsets within the line where wrapping should occur.
        """
        ...
    
    def get_tab_widths(self, line_index: int) -> list[int]:
        """Return a list of the tab widths for the given line index.

        Args:
            line_index: The index of the line in the document.

        Returns:
            An ordered list of the expanded width of the tabs in the line.
        """
        ...
    


