"""
This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures
import io
import sys
import warnings
from __future__ import annotations
from collections import deque
from collections.abc import Iterable
from uvicorn._types import ASGIReceiveCallable, ASGIReceiveEvent, ASGISendCallable, ASGISendEvent, Environ, ExcInfo, HTTPRequestEvent, HTTPResponseBodyEvent, HTTPResponseStartEvent, HTTPScope, StartResponse, WSGIApp
from a2wsgi import WSGIMiddleware

def build_environ(scope: HTTPScope, message: ASGIReceiveEvent, body: io.BytesIO) -> Environ:
    """
    Builds a scope and request message into a WSGI environ object.
    """
    ...

class _WSGIMiddleware:
    def __init__(self, app: WSGIApp, workers: int = ...) -> None:
        ...
    
    async def __call__(self, scope: HTTPScope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


class WSGIResponder:
    def __init__(self, app: WSGIApp, executor: concurrent.futures.ThreadPoolExecutor, scope: HTTPScope) -> None:
        ...
    
    async def __call__(self, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    
    async def sender(self, send: ASGISendCallable) -> None:
        ...
    
    def start_response(self, status: str, response_headers: Iterable[tuple[str, str]], exc_info: ExcInfo | None = ...) -> None:
        ...
    
    def wsgi(self, environ: Environ, start_response: StartResponse) -> None:
        ...
    


