"""
This type stub file was generated by pyright.
"""

import typing
from __future__ import annotations
from starlette._exception_handler import ExceptionHandlers, StatusHandlers, wrap_app_handling_exceptions
from starlette.exceptions import HTTPException, WebSocketException
from starlette.requests import Request
from starlette.responses import PlainTextResponse, Response
from starlette.types import ASGIApp, Receive, Scope, Send
from starlette.websockets import WebSocket

class ExceptionMiddleware:
    def __init__(self, app: ASGIApp, handlers: typing.Mapping[typing.Any, typing.Callable[[Request, Exception], Response]] | None = ..., debug: bool = ...) -> None:
        ...
    
    def add_exception_handler(self, exc_class_or_status_code: int | type[Exception], handler: typing.Callable[[Request, Exception], Response]) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    def http_exception(self, request: Request, exc: Exception) -> Response:
        ...
    
    async def websocket_exception(self, websocket: WebSocket, exc: Exception) -> None:
        ...
    


