"""
This type stub file was generated by pyright.
"""

import multiprocessing
import os
import sys
from __future__ import annotations
from multiprocessing.context import SpawnProcess
from socket import socket
from typing import Callable
from uvicorn.config import Config

"""
Some light wrappers around Python's multiprocessing, to deal with cleanly
starting child processes.
"""
spawn = ...
def get_subprocess(config: Config, target: Callable[..., None], sockets: list[socket]) -> SpawnProcess:
    """
    Called in the parent process, to instantiate a new child process instance.
    The child is not yet started at this point.

    * config - The Uvicorn configuration instance.
    * target - A callable that accepts a list of sockets. In practice this will
               be the `Server.run()` method.
    * sockets - A list of sockets to pass to the server. Sockets are bound once
                by the parent process, and then passed to the child processes.
    """
    ...

def subprocess_started(config: Config, target: Callable[..., None], sockets: list[socket], stdin_fileno: int | None) -> None:
    """
    Called when the child process starts.

    * config - The Uvicorn configuration instance.
    * target - A callable that accepts a list of sockets. In practice this will
               be the `Server.run()` method.
    * sockets - A list of sockets to pass to the server. Sockets are bound once
                by the parent process, and then passed to the child processes.
    * stdin_fileno - The file number of sys.stdin, so that it can be reattached
                     to the child process.
    """
    ...

