"""
This type stub file was generated by pyright.
"""

import logging
from __future__ import annotations
from collections.abc import Iterator
from pathlib import Path
from socket import socket
from typing import Callable
from uvicorn.config import Config
from uvicorn.supervisors.basereload import BaseReload

logger = ...
class StatReload(BaseReload):
    def __init__(self, config: Config, target: Callable[[list[socket] | None], None], sockets: list[socket]) -> None:
        ...
    
    def should_restart(self) -> list[Path] | None:
        ...
    
    def restart(self) -> None:
        ...
    
    def iter_py_files(self) -> Iterator[Path]:
        ...
    


