"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from fractions import Fraction
from typing import TYPE_CHECKING
from textual._resolve import resolve_box_models
from textual.geometry import NULL_OFFSET, Region, Size, Spacing
from textual.layout import ArrangeResult, Layout, WidgetPlacement
from textual.widget import Widget

if TYPE_CHECKING:
    ...
class HorizontalLayout(Layout):
    """Used to layout Widgets horizontally on screen, from left to right. Since Widgets naturally
    fill the space of their parent container, all widgets used in a horizontal layout should have a specified.
    """
    name = ...
    def arrange(self, parent: Widget, children: list[Widget], size: Size) -> ArrangeResult:
        ...
    


