"""
This type stub file was generated by pyright.
"""

import codecs
import queue
import threading
from __future__ import annotations
from typing import Any, Callable, Iterable, Iterator
from ..exceptions import ConcurrencyError
from ..frames import Frame, OP_BINARY, OP_CONT, OP_TEXT
from ..typing import Data
from .utils import Deadline

__all__ = ["Assembler"]
UTF8Decoder = ...
class Assembler:
    """
    Assemble messages from frames.

    :class:`Assembler` expects only data frames. The stream of frames must
    respect the protocol; if it doesn't, the behavior is undefined.

    Args:
        pause: Called when the buffer of frames goes above the high water mark;
            should pause reading from the network.
        resume: Called when the buffer of frames goes below the low water mark;
            should resume reading from the network.

    """
    def __init__(self, high: int | None = ..., low: int | None = ..., pause: Callable[[], Any] = ..., resume: Callable[[], Any] = ...) -> None:
        ...
    
    def get_next_frame(self, timeout: float | None = ...) -> Frame:
        ...
    
    def reset_queue(self, frames: Iterable[Frame]) -> None:
        ...
    
    def get(self, timeout: float | None = ..., decode: bool | None = ...) -> Data:
        """
        Read the next message.

        :meth:`get` returns a single :class:`str` or :class:`bytes`.

        If the message is fragmented, :meth:`get` waits until the last frame is
        received, then it reassembles the message and returns it. To receive
        messages frame by frame, use :meth:`get_iter` instead.

        Args:
            timeout: If a timeout is provided and elapses before a complete
                message is received, :meth:`get` raises :exc:`TimeoutError`.
            decode: :obj:`False` disables UTF-8 decoding of text frames and
                returns :class:`bytes`. :obj:`True` forces UTF-8 decoding of
                binary frames and returns :class:`str`.

        Raises:
            EOFError: If the stream of frames has ended.
            UnicodeDecodeError: If a text frame contains invalid UTF-8.
            ConcurrencyError: If two coroutines run :meth:`get` or
                :meth:`get_iter` concurrently.
            TimeoutError: If a timeout is provided and elapses before a
                complete message is received.

        """
        ...
    
    def get_iter(self, decode: bool | None = ...) -> Iterator[Data]:
        """
        Stream the next message.

        Iterating the return value of :meth:`get_iter` yields a :class:`str` or
        :class:`bytes` for each frame in the message.

        The iterator must be fully consumed before calling :meth:`get_iter` or
        :meth:`get` again. Else, :exc:`ConcurrencyError` is raised.

        This method only makes sense for fragmented messages. If messages aren't
        fragmented, use :meth:`get` instead.

        Args:
            decode: :obj:`False` disables UTF-8 decoding of text frames and
                returns :class:`bytes`. :obj:`True` forces UTF-8 decoding of
                binary frames and returns :class:`str`.

        Raises:
            EOFError: If the stream of frames has ended.
            UnicodeDecodeError: If a text frame contains invalid UTF-8.
            ConcurrencyError: If two coroutines run :meth:`get` or
                :meth:`get_iter` concurrently.

        """
        ...
    
    def put(self, frame: Frame) -> None:
        """
        Add ``frame`` to the next message.

        Raises:
            EOFError: If the stream of frames has ended.

        """
        ...
    
    def maybe_pause(self) -> None:
        """Pause the writer if queue is above the high water mark."""
        ...
    
    def maybe_resume(self) -> None:
        """Resume the writer if queue is below the low water mark."""
        ...
    
    def close(self) -> None:
        """
        End the stream of frames.

        Calling :meth:`close` concurrently with :meth:`get`, :meth:`get_iter`,
        or :meth:`put` is safe. They will raise :exc:`EOFError`.

        """
        ...
    


