"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from rich.color import Color

def blend_colors(color1: Color, color2: Color, ratio: float) -> Color:
    """Given two RGB colors, return a color that sits some distance between
    them in RGB color space.

    Args:
        color1: The first color.
        color2: The second color.
        ratio: The ratio of color1 to color2.

    Returns:
        A Color representing the blending of the two supplied colors.
    """
    ...

