"""
This type stub file was generated by pyright.
"""

import typing
from __future__ import annotations
from .._synchronization import current_async_library
from .base import AsyncNetworkBackend, AsyncNetworkStream, SOCKET_OPTION

class AutoBackend(AsyncNetworkBackend):
    async def connect_tcp(self, host: str, port: int, timeout: float | None = ..., local_address: str | None = ..., socket_options: typing.Iterable[SOCKET_OPTION] | None = ...) -> AsyncNetworkStream:
        ...
    
    async def connect_unix_socket(self, path: str, timeout: float | None = ..., socket_options: typing.Iterable[SOCKET_OPTION] | None = ...) -> AsyncNetworkStream:
        ...
    
    async def sleep(self, seconds: float) -> None:
        ...
    


